[tools]
awscli = "latest"
ghq = "latest"
github-cli = "latest"
go = "latest"
neovim = "latest"
node = "lts"
python = "latest"
ruby = "latest"
rust = "latest"
starship = "latest"
uv = "latest"

[settings]
idiomatic_version_file_enable_tools = ["ruby"]
experimental = true
